# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          pip install poetry
          poetry install
      - name: Mypy check
        run: |
          poetry run mypy .
      - name: Pylint
        run: |
          poetry run pylint python_design_patterns
      - name: Isort
        run: |
          poetry run isort python_design_patterns --recursive --check-only
      - name: Code format check
        run: |
          poetry run yapf -rd python_design_patterns
      - name: Test
        run: |
          poetry run pytest --junitxml=junit/test-results.xml --cov=python_design_patterns --cov-report=term-missing --cov-report=xml --doctest-modules
